In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt 

In [3]:
data=pd.read_csv('flight_delays_train.csv')
data



Month DayofMonth DayOfWeek  DepTime UniqueCarrier Origin Dest  Distance  \
0       c-8       c-21       c-7     1934            AA    ATL  DFW       732   
1       c-4       c-20       c-3     1548            US    PIT  MCO       834   
2       c-9        c-2       c-5     1422            XE    RDU  CLE       416   
3      c-11       c-25       c-6     1015            OO    DEN  MEM       872   
4      c-10        c-7       c-6     1828            WN    MDW  OMA       423   
...     ...        ...       ...      ...           ...    ...  ...       ...   
99995   c-5        c-4       c-3     1618            OO    SFO  RDD       199   
99996   c-1       c-18       c-3      804            CO    EWR  DAB       884   
99997   c-1       c-24       c-2     1901            NW    DTW  IAH      1076   
99998   c-4       c-27       c-4     1515            MQ    DFW  GGG       140   
99999  c-11       c-17       c-4     1800            WN    SEA  SMF       605   

      dep_delayed_15min  
0                     N  
1                     N  
2                     N  
3                     N  
4                     Y  
...                 ...  
99995                 N  
99996                 N  
99997                 N  
99998                 N  
99999                 N  

[100000 rows x 9 columns]

In [21]:
data.isnull().any()

Month                False
DayofMonth           False
DayOfWeek            False
DepTime              False
UniqueCarrier        False
Origin               False
Dest                 False
Distance             False
dep_delayed_15min    False
dtype: bool

In [4]:
#converting data into input x and output y and converting string to int.
y=data['dep_delayed_15min'].values
x=data[['Month','DayofMonth','DayOfWeek','DepTime','UniqueCarrier','Origin','Dest','Distance']].values
y.reshape(100000,1);
from sklearn.preprocessing import LabelEncoder  

le = LabelEncoder()  #converting to int.
y=le.fit_transform(y)
#feature normalization:
x1=le.fit_transform(data['Month'].values)
x1=x1/np.max(x1)
x2=le.fit_transform(data['DayofMonth'].values)
x2=x2/np.max(x2)
x3=le.fit_transform(data['DayOfWeek'].values)
x3=x3/np.max(x3)
x4=le.fit_transform(data['DepTime'].values)
x4=x4/np.max(x4)
x5=le.fit_transform(data['UniqueCarrier'].values)
x5=x5/np.max(x5)
x6=le.fit_transform(data['Origin'].values)
x6=x6/np.max(x6)
x7=le.fit_transform(data['Dest'].values)
x7=x7/np.max(x7)
x8=le.fit_transform(data['Distance'].values)
x8=x1/np.max(x8)
X=np.array([x1,x2,x3,x4,x5,x6,x7,x8]).T

X


array([[9.09090909e-01, 4.33333333e-01, 1.00000000e+00, ...,
        6.25000000e-02, 2.70833333e-01, 6.94492673e-04],
       [5.45454545e-01, 4.00000000e-01, 3.33333333e-01, ...,
        7.53472222e-01, 5.93750000e-01, 4.16695604e-04],
       [1.00000000e+00, 3.66666667e-01, 6.66666667e-01, ...,
        7.91666667e-01, 2.04861111e-01, 7.63941940e-04],
       ...,
       [0.00000000e+00, 5.33333333e-01, 1.66666667e-01, ...,
        2.95138889e-01, 4.54861111e-01, 0.00000000e+00],
       [5.45454545e-01, 6.33333333e-01, 5.00000000e-01, ...,
        2.74305556e-01, 3.71527778e-01, 4.16695604e-04],
       [1.81818182e-01, 2.66666667e-01, 5.00000000e-01, ...,
        8.50694444e-01, 8.78472222e-01, 1.38898535e-04]])

In [5]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
X_new = SelectKBest(chi2, k=5).fit_transform(X, y)
print(X_new)
#Dayofmonth,day of week,DepTime,origin,Distance are selected as best 5 features which affect more on output

[[0.90909091 0.43333333 1.         0.78290993 0.0625    ]
 [0.54545455 0.4        0.33333333 0.60892995 0.75347222]
 [1.         0.36666667 0.66666667 0.54272517 0.79166667]
 ...
 [0.         0.53333333 0.16666667 0.75750577 0.29513889]
 [0.54545455 0.63333333 0.5        0.58352579 0.27430556]
 [0.18181818 0.26666667 0.5        0.71054657 0.85069444]]


In [6]:
test_data=pd.read_csv('flight_delays_test.csv')
test_data


Month DayofMonth DayOfWeek  DepTime UniqueCarrier Origin Dest  Distance
0       c-7       c-25       c-3      615            YV    MRY  PHX       598
1       c-4       c-17       c-2      739            WN    LAS  HOU      1235
2      c-12        c-2       c-7      651            MQ    GSP  ORD       577
3       c-3       c-25       c-7     1614            WN    BWI  MHT       377
4       c-6        c-6       c-3     1505            UA    ORD  STL       258
...     ...        ...       ...      ...           ...    ...  ...       ...
99995   c-6        c-5       c-2      852            WN    CRP  HOU       187
99996  c-11       c-24       c-6     1446            UA    ORD  LAS      1515
99997   c-1       c-30       c-2     1509            OO    ORD  SGF       438
99998   c-1        c-5       c-5      804            DL    LGA  ATL       761
99999  c-10       c-29       c-1      834            OO    MKE  MSP       297

[100000 rows x 8 columns]

In [7]:
test=test_data[['DayofMonth','DayOfWeek','DepTime','Origin','Distance']].values
test

array([['c-25', 'c-3', 615, 'MRY', 598],
       ['c-17', 'c-2', 739, 'LAS', 1235],
       ['c-2', 'c-7', 651, 'GSP', 577],
       ...,
       ['c-30', 'c-2', 1509, 'ORD', 438],
       ['c-5', 'c-5', 804, 'LGA', 761],
       ['c-29', 'c-1', 834, 'MKE', 297]], dtype=object)

In [8]:
x1_test=le.fit_transform(data['DayofMonth'].values)
x1_test=x1_test/np.average(x1_test)
x2_test=le.fit_transform(data['DayOfWeek'].values)
x2_test=x2_test/np.average(x2_test)
x3_test=le.fit_transform(data['DepTime'].values)
x3_test=x3_test/np.average(x3_test)
x4_test=le.fit_transform(data['Origin'].values)
x4_test=x4_test/np.average(x4_test)
x5_test=le.fit_transform(data['Distance'].values)
x5_test=x5_test/np.average(x5_test)
X_test=np.array([x1_test,x2_test,x3_test,x4_test,x5_test]).T
X_test

array([[0.87696102, 2.03263738, 1.54004359, 0.12642419, 1.15440988],
       [0.80950248, 0.67754579, 1.19781168, 1.52411391, 1.30246245],
       [0.74204394, 1.35509159, 1.06758184, 1.60137314, 0.61221737],
       ...,
       [1.07933664, 0.3387729 , 1.49007167, 0.59700314, 1.65658819],
       [1.28171226, 1.01631869, 1.14783976, 0.55486174, 0.11003907],
       [0.53966832, 1.01631869, 1.39769934, 1.72077376, 0.93833316]])

In [9]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_new, y);

ynew =(model.predict(X_new))
ynew

array([0, 0, 0, ..., 0, 0, 0])

In [10]:
from sklearn.metrics import accuracy_score
accuracy_score(y, ynew)

0.80956

In [11]:
#using logistic regression:
from sklearn.linear_model import LogisticRegression
logisticRegr = LogisticRegression()
logisticRegr.fit(X_new,y)
Ylogreg =(logisticRegr.predict(X_new))
accuracy_score(y, Ylogreg)

0.80956

In [12]:
#using decision trees:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_new, y)

In [13]:
YY=clf.predict(X_new)

In [14]:
YY

array([0, 0, 0, ..., 0, 0, 0])

In [15]:
accuracy_score(y, YY)

0.99959

In [17]:
Ytest=clf.predict(X_test)

In [18]:
Ytest    #prediction

array([0, 1, 0, ..., 1, 0, 1])